#!/usr/bin/env bash
# post-edit-typecheck.sh — PostToolUse hook (Edit|Write|MultiEdit)
# Scoped, fast typecheck of just the touched tsconfig project after a source
# edit, so type errors surface immediately instead of at CI or build time.
# Advisory only — never blocks (edits mid-refactor legitimately have transient
# type errors across files); prints failures to stderr for Claude to see.
#
# This repo has NO dedicated `typecheck`/`type-check` npm script (`build` runs
# `vite build`, which does not type-check). It has two tsconfigs instead:
#   - tsconfig.json          — Worker root (src/worker, src/shared), excludes src/pwa
#   - src/pwa/tsconfig.json  — PWA app (src/pwa, ../shared -> src/shared)
# `worker-configuration.d.ts` (generated by `wrangler types`) is already
# committed at the repo root, so plain `npx tsc --noEmit -p <tsconfig>` works
# without needing to regenerate it on every edit.

set -uo pipefail

ROOT="/Users/jboles/vibe-projects/foodbox-data-app"
INPUT=$(cat)

FILE_PATH=$(echo "$INPUT" | python3 -c "import json,sys; print(json.load(sys.stdin).get('tool_input',{}).get('file_path',''))" 2>/dev/null)

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi
case "$FILE_PATH" in
  *.ts|*.tsx) ;;
  *) exit 0 ;;
esac

cd "$ROOT" || exit 0

run_tsc() {
  local label="$1" cfg="$2"
  local output status
  output=$(npx tsc --noEmit -p "$cfg" 2>&1)
  status=$?
  if [ "$status" -ne 0 ]; then
    echo "[post-edit-typecheck] $label ($cfg) failed typecheck after editing $(basename "$FILE_PATH"):" >&2
    echo "$output" | tail -30 >&2
  fi
}

case "$FILE_PATH" in
  *"/src/pwa/"*)
    run_tsc "pwa" "src/pwa/tsconfig.json"
    ;;
  *"/src/shared/"*)
    # Shared code is included by both tsconfigs — check both.
    run_tsc "worker" "tsconfig.json"
    run_tsc "pwa" "src/pwa/tsconfig.json"
    ;;
  *"/src/"*)
    run_tsc "worker" "tsconfig.json"
    ;;
  *)
    # tests/, scripts/, etc. — not covered by either tsconfig's include; skip.
    exit 0
    ;;
esac

exit 0
