CREATE TABLE IF NOT EXISTS question_settings (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  field_name TEXT NOT NULL UNIQUE,
  label_en TEXT NOT NULL,
  label_es TEXT NOT NULL,
  hint_en TEXT,
  hint_es TEXT,
  input_type TEXT NOT NULL CHECK (input_type IN (
    'text', 'phone', 'number', 'select', 'multiselect', 'yesno', 'yesno_declined', 'income'
  )),
  options_en TEXT,
  options_es TEXT,
  visible INTEGER NOT NULL DEFAULT 1,
  required INTEGER NOT NULL DEFAULT 0,
  display_order INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_question_settings_order
  ON question_settings(display_order);

INSERT OR IGNORE INTO question_settings
  (id, field_name, label_en, label_es, hint_en, hint_es,
   input_type, options_en, options_es, visible, required, display_order)
VALUES
  ('qs01', 'language',
   'What language do you prefer?',
   '¿Qué idioma prefiere?',
   NULL, NULL,
   'select',
   '["English","Spanish","Other"]',
   '["Inglés","Español","Otro"]',
   1, 0, 10),

  ('qs02', 'name',
   'Family last name',
   'Apellido familiar',
   'Enter the last name used to identify this household.',
   'Ingrese el apellido que se usa para identificar a este hogar.',
   'text',
   NULL, NULL,
   1, 1, 20),

  ('qs03', 'phone',
   'Phone number',
   'Número de teléfono',
   'Enter digits only. Leave blank if no phone.',
   'Solo dígitos. Deje en blanco si no tiene teléfono.',
   'phone',
   NULL, NULL,
   1, 0, 30),

  ('qs04', 'address',
   'Home address',
   'Dirección de casa',
   NULL, NULL,
   'text',
   NULL, NULL,
   1, 0, 40),

  ('qs05', 'zip_code',
   'ZIP code',
   'Código postal',
   NULL, NULL,
   'text',
   NULL, NULL,
   1, 0, 50),

  ('qs06', 'num_people',
   'How many people live in your household?',
   '¿Cuántas personas viven en su hogar?',
   'Include everyone who lives there, including yourself.',
   'Incluya a todos los que viven allí, incluyéndose usted.',
   'number',
   NULL, NULL,
   1, 0, 60),

  ('qs07', 'num_children_under_18',
   'How many children under 18 live in your household?',
   '¿Cuántos niños menores de 18 años viven en su hogar?',
   NULL, NULL,
   'number',
   NULL, NULL,
   1, 0, 70),

  ('qs08', 'num_children_under_5',
   'How many children under 5 live in your household?',
   '¿Cuántos niños menores de 5 años viven en su hogar?',
   NULL, NULL,
   'number',
   NULL, NULL,
   1, 0, 80),

  ('qs09', 'num_with_diabetes',
   'How many household members have diabetes?',
   '¿Cuántos miembros del hogar tienen diabetes?',
   NULL, NULL,
   'number',
   NULL, NULL,
   1, 0, 90),

  ('qs10', 'ethnicity',
   'What is your race or ethnicity?',
   '¿Cuál es su raza o etnia?',
   'Select all that apply.',
   'Seleccione todas las que correspondan.',
   'multiselect',
   '["American Indian or Alaska Native","Asian","Black or African American","Native Hawaiian or Other Pacific Islander","White","Multiracial","Other","Prefer not to say"]',
   '["Indígena americano o nativo de Alaska","Asiático","Negro o afroamericano","Nativo de Hawái u otro isleño del Pacífico","Blanco","Multirracial","Otro","Prefiero no decir"]',
   1, 0, 100),

  ('qs11', 'hispanic',
   'Do you identify as Hispanic or Latino?',
   '¿Se identifica como hispano o latino?',
   NULL, NULL,
   'yesno_declined',
   NULL, NULL,
   1, 0, 110),

  ('qs12', 'health_insurance',
   'Does anyone in your household have health insurance?',
   '¿Alguien en su hogar tiene seguro médico?',
   NULL, NULL,
   'yesno_declined',
   NULL, NULL,
   1, 0, 120),

  ('qs13', 'snap_benefits',
   'Does your household receive SNAP benefits (food stamps)?',
   '¿Su hogar recibe beneficios SNAP (cupones de alimentos)?',
   NULL, NULL,
   'yesno_declined',
   NULL, NULL,
   1, 0, 130),

  ('qs14', 'ami_bracket',
   'What is your household income?',
   '¿Cuál es el ingreso de su hogar?',
   'We use this to understand community needs. Your answer stays private. (options_en/es = pay period choices for the income calculator widget)',
   'Usamos esto para entender las necesidades de la comunidad. Su respuesta es privada.',
   'income',
   '["weekly","biweekly","monthly","yearly"]',
   '["semanal","quincenal","mensual","anual"]',
   1, 0, 140),

  ('qs15', 'receives_texts',
   'Can we send you text messages?',
   '¿Podemos enviarle mensajes de texto?',
   'We only send messages about picking up food.',
   'Solo enviamos mensajes sobre la recogida de alimentos.',
   'yesno',
   NULL, NULL,
   1, 0, 150),

  ('qs16', 'want_text_updates',
   'Would you like reminders about upcoming food distribution events?',
   '¿Le gustaría recordatorios sobre próximos eventos de distribución de alimentos?',
   NULL, NULL,
   'yesno',
   NULL, NULL,
   1, 0, 160),

  ('qs17', 'id_confirmed',
   'ID confirmed',
   'ID confirmado',
   NULL, NULL,
   'yesno',
   NULL, NULL,
   1, 1, 170),

  ('qs18', 'bag_received',
   'Bag received',
   'Bolsa recibida',
   NULL, NULL,
   'yesno',
   NULL, NULL,
   1, 1, 180);

INSERT OR IGNORE INTO question_settings
  (id, field_name, label_en, label_es, hint_en, hint_es,
   input_type, options_en, options_es, visible, required, display_order)
VALUES
  ('qs19', 'date_of_birth',
   'Date of birth',
   'Fecha de nacimiento',
   'Format: MM/DD/YYYY',
   'Formato: MM/DD/AAAA',
   'text',
   NULL, NULL,
   0, 0, 35);
